name: vedanta_lrms
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.18.6 <3.0.0'
  # sdk: '>=3.1.2 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.1
  flutter_login_facebook: ^1.7.0
  google_sign_in: ^6.1.6
  smooth_page_indicator: ^1.0.1
  pin_code_fields: ^8.0.1
  sms_autofill: ^2.2.0
  intl: ^0.18.0
  permission_handler: ^11.1.0
  images_picker: ^1.2.11
  flutter_otp_text_field: ^1.1.1
  colorful_safe_area: ^1.0.0
  flutter_time_picker_spinner: ^2.0.0
  flutter_screenutil: ^5.9.0
  google_maps_flutter: ^2.5.0
  flutter_speed_dial: ^7.0.0
  animated_expandable_fab: ^0.0.2
  geolocator: ^10.1.0
  qr_code_scanner: ^1.0.1
  image_picker: ^1.0.4
  image: ^4.1.3
  qr_code_utils: ^0.0.1
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  http: ^1.1.2
  flutter_map: ^6.1.0
  flutter_map_geojson: ^1.0.6
  location: ^5.0.3
  device_info_plus: ^9.1.1
  latlong2: ^0.9.0
  modal_bottom_sheet: ^2.1.2
  badges: ^3.1.2
  url_launcher: ^6.2.2
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
