name: truck_booking_app
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.18.6 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^3.0.3
  shared_preferences: ^2.0.17
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.1
  flutter_login_facebook: ^1.7.0
  google_sign_in: ^5.4.4
  smooth_page_indicator: ^1.0.1
  pin_code_fields: ^7.4.0
  sms_autofill: ^2.2.0
  intl: ^0.18.0
  permission_handler: ^10.2.0
  images_picker: ^1.2.11
  flutter_otp_text_field: ^1.1.1
  colorful_safe_area: ^0.3.0
  flutter_time_picker_spinner: ^2.0.0
  flutter_screenutil: ^5.9.0
  google_maps_flutter: ^2.5.0
  flutter_speed_dial: ^7.0.0
  animated_expandable_fab: ^0.0.2
  geolocator: ^10.1.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
